epub: Switch to proficiencies by type
The epub output format didn't list any proficiencies anymore
since various recent changes I made. This patch fixes that problem.

I worked around an issue in the epub gm files output, where it is possible
to have a monster as a character. In that case, proficiencies_by_type is
not initialised, resulting in the following error:

jinja2.exceptions.UndefinedError: 'dungeonsheets.monsters.monsters_v.Veteran
object' has no attribute 'proficiencies_by_type'

It does make me think whether is would be possible to rename the
proficiencies_by_type method to proficiencies_text, which will be initialised
by definition, and then use rst and a jinja filter for formatting instead...