latex character template: Allow more reStructuredText
Feed more content of the latex character sheet through the
latex jinja filter, so that users can used reStructuredText
to format their treasure, backstory, etcetera, while making
use of, e.g., bulleted lists.

Needed to explicitly add appearance_text as an attribyte to
character.py, to prevent jinja2.exceptions.UndefinedError:
'dungeonsheets.character.Character object' has no attribute 'appearance_text'